package com.gateway.networkparam.entity

data class ServiceState(
    val cdmaNetworkId: Int? = null,
    val cdmaSystemId: Int? = null,
    val cellBandwidths: List<Int>? = null,
    val channelNumber: Int? = null,
    val duplexMode: String? = null,
    val isManualSelection: Boolean? = null,
    val operatorAlphaLong: String? = null,
    val operatorAlphaShort: String? = null,
    val operatorNumeric: String? = null,
    val roaming: Boolean? = null,
    val voiceRegState: String? = null,
    val isSearching: Boolean? = null,
    val networkRegistrationInfoList: List<NetworkRegistrationInfo> = emptyList(),
    val bitmaskHasTech: Boolean? = null,
    val cdmaDefaultRoamingIndicator: Int? = null,
    val cdmaEriIconIndex: Int? = null,
    val cdmaEriIconMode: Int? = null,
    val cdmaRoamingIndicator: Int? = null,
    val configRadioTechnology: Int? = null,
    val dataRegState: String? = null,
    val hwNetworkType: Int? = null,
    val networkRegistrationInfo: NetworkRegistrationInfo? = null,
    val networkRegistrationInfoListForDomain: List<NetworkRegistrationInfo> = emptyList(),
    val networkRegistrationInfoListForTransportType: List<NetworkRegistrationInfo> = emptyList(),
    val nsaState: Int? = null,
    val radioTechnology: Int? = null,
    val rilDataRadioTechnology: Int? = null,
    val rilVoiceRadioTechnology: Int? = null,
    val isCdma: Boolean? = null,
    val isEmergencyOnly: Boolean? = null,
    val isGsm: Boolean? = null,
    val isHrpd1X: Boolean? = null
)
